### ISSUE TITLE
Bug when not have internet

### ISSUE THREAD

**Issue by lngvnsang** [huubao2309/interview_project#1]
Hello anh, em có tham khảo project này của anh, thật sự cấu trúc code của anh rất hay, thank anh đã chia sẽ
Nhưng em gặp 1 vấn đề với code, khi mở app ở page home mà ko có internet thì dialog không đóng đc ạ, khi bật wifi lại vẫn ko đc, các màng hình khác khi mở lại thì đc, em đã tự fix nhưng không đc. Mong anh giúp đỡ ạ

https://user-images.githubusercontent.com/76673112/167451962-b698d5b3-fe83-4287-abaf-ef57309ad3db.mp4

**Comment by lngvnsang** [comment]
Vấn đề xuất hiện khi có 2 dialog xếp chồng lên nhau, em newbie nên không rõ lắm :((
Error: Unhandled Exception: Bad state: Future already completed

**Comment by huubao2309** [comment]
waiting for fixing bug

**Comment by huubao2309** [comment]
@lvsang1504 This is my old project.
Please view new project https://github.com/huubao2309/interview_getx
